# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Key
tagline:          Creatividad digital
url:              http://key.kim
paginate:         1
baseurl:          /
author:
  name:           Odice
  url:            https://twitter.com/odice
  email:          im@odice.me

# Custom vars
version:          1.0.0
github:
  repo:           https://key.kim
