# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Key
tagline:          'Kim'
description:      'Creatividad Digital'
url:              http://key.kim

author:
  name:           'Odice'
  url:            https://twitter.com/odice

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/odice/key
